#ifndef KG3DSCENERESPONSETYPE_H
#define KG3DSCENERESPONSETYPE_H

//EntityID布局：             MASK(2) : INSCENE(30) 或者 MASK(2) : INPVS[ PVSID(16) : ENTITYID(14) ]
#define  MASK_INPVS             0x40000000
#define  MASK_PVSID				0x0000ffff
#define  MASK_ENTITYID_INPVS    0x00003fff
#define  MAX_ENTITYID_INSCENE   0x3fffffff
#define  MAX_ENTITYID_INPVS     0x00003fff
#define  MAX_PVSID              0x0000ffff    

#define INVALID_PROPERTY_NPCID (-1)

typedef enum KSRSTATE_CONDITION
{
	KSRSTATE_CONDITION_NONE = -1,
	KSRSTATE_CONDITION_AND = 0,
	KSRSTATE_CONDITION_OR = 1,
	KSRSTATE_CONDITION_NOT = 2,
	KSRSTATE_CONDITION_XOR = 3,
	KSRSTATE_CONDITION_DISTANCE_LONGER = 4,
	KSRSTATE_CONDITION_DISTANCE_SHORTER = 5,
	KSRSTATE_CONDITION_DISTANCE_EQUAL = 6,
	KSRSTATE_CONDITION_TIMEOUT = 7,
	KSRSTATE_CONDITION_ANIFINISHED = 8,
	KSRSTATE_CONDITION_ANICOUNT = 9,
	KSRSTATE_CONDITION_DAMAGE = 10,
	KSRSTATE_CONDITION_ATTACK = 11,
	KSRSTATE_CONDITION_HP_EQUAL = 10001,          //这些枚举值涉及到存盘,值需要固定
	KSRSTATE_CONDITION_HP_HIGHER = 10002,
	KSRSTATE_CONDITION_HP_LOWER = 10003,
}_KSRSTATE_CONDITION;

typedef enum KSRSTATE_BEHAVIOR
{
	KSRSTATE_BEHAVIOR_NONE = -1,
	KSRSTATE_BEHAVIOR_RANDOM,
	KSRSTATE_BEHAVIOR_CONDITION,
	KSRSTATE_BEHAVIOR_CLEARDAMAGE,
}_KSRSTATE_BEHAVIOR;

typedef enum KSRSTATE_PROPERTY
{
	KSRSTATE_PROPERTY_NONE = -1,
	KSRSTATE_PROPERTY_DISTANCE = 0,
	KSRSTATE_PROPERTY_DAMAGE = 1,
	KSRSTATE_PROPERTY_BEATTACKEDSUSTAINEDTIME = 2,
	KSRSTATE_PROPERTY_POSITION = 3,
	KSRSTATE_PROPERTY_ROTATION = 4,
	KSRSTATE_PROPERTY_SCALING = 5,
	KSRSTATE_PROPERTY_DISPLAYLEVEL = 6,
	KSRSTATE_PROPERTY_HP = 7,
	KSRSTATE_PROPERTY_NPCID = 8,
}_KSRSTATE_PROPERTY;
typedef enum KSRSTATE_PROPERTY_OP
{
	KSRSTATE_PROPERTY_OP_ADD,    // 加法
	KSRSTATE_PROPERTY_OP_CHANGE, // 替换原参数
}_KSRSTATE_PROPERTY_OP;
typedef enum KSRSTATE_COMMAND
{
	KSRSTATE_COMMAND_BEATTACKED = 0,
	KSRSTATE_COMMAND_DYNAMICLOAD = 1,
	KSRSTATE_COMMAND_DYNAMICUNLOAD = 2,
	KSRSTATE_COMMAND_SWITCHSTATE = 3,
}_KSRSTATE_COMMAND;

enum 
{
	KSR_NONE = 0x0000,
	KSR_CLIENT = 0x0001,
};

struct KSROption
{
	DWORD dwDisplayLevel;
};
#endif