
// Cpp include file
// ASProtect Envelope checking routine (for function checking)

#ifndef __BORLANDC__
__asm
#endif
{

  ENVELOPE_CHECK_FUNC ENVELOPE_CHECK_FUNC_BUFFER // 10

  DEFAULT_BUFFER      DEFAULT_BUFFER             // 20
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 30
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 40
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 50
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 60
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 70
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 80
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 90
  DEFAULT_BUFFER      DEFAULT_BUFFER             // A0
  DEFAULT_BUFFER      DEFAULT_BUFFER             // B0
  DEFAULT_BUFFER      DEFAULT_BUFFER             // C0
  DEFAULT_BUFFER      DEFAULT_BUFFER             // D0
  DEFAULT_BUFFER      DEFAULT_BUFFER             // E0
  DEFAULT_BUFFER      DEFAULT_BUFFER             // F0
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 100
  DEFAULT_BUFFER      DEFAULT_BUFFER             // 110

};